### ISSUE TITLE
README

### ISSUE THREAD

**Issue by pniedzwiedzinski** [xPatricki/ZSKGEON#1]
Siema,

Jako wujek dobra rada przesyłam ci to: https://www.markdownguide.org/basic-syntax/ (`md` => markdown). Markdown stał się trochę standardem jeśli chodzi o opisywanie projektu itp, bo jest po prostu prosty a można robić wszystko co można w htmlu. Prawdę mówiąc można tak naprawdę pisać html w markdownie jak chcesz zrobić jakieś customowe stylowanie, ramki itd.

Jest jeszcze [ReST](https://docutils.sourceforge.io/docs/user/rst/quickref.html) z rozszerzeniem `rst` ale go się rzadziej używa (bo się trudniej pisze :smile:)

Dlatego `README.md` a nie `read.me` :wink:

**Comment by xPatricki** [comment]
Dzięki wielkie, zaraz obczaj, bo wczoraj jedynie coś koło 1:00 chciałem
tylko repo stworzyc generalnie ale już nie miałem siły wymyślać co tam
wpisać

śr., 18 mar 2020, 08:50 użytkownik Patryk Niedźwiedziński <
notifications@github.com> napisał:
